name: CI

on:
    pull_request:
    push:
        branches:
            - master
            - feature/[a-z]+-[0-9]+/dev-*
    workflow_dispatch:

jobs:
    validation:
        name: "CS, ArchSniffer, PHPStan, Security"
        runs-on: "ubuntu-latest"
        env:
            APPLICATION_ENV: testing
        strategy:
            fail-fast: false
            matrix:
                php-version: [
                    '7.4',
                    '8.1'
                ]
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, intl, pdo_mysql, redis
                  tools: composer:v2

            - name: Composer get cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Composer cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer validate
              run: composer validate

            - name: Composer version
              run: composer --version

            - name: Composer install
              run: composer install --optimize-autoloader

            - name: Run PHPStan
              run: composer stan

# Disabled, needs further investigation for re-enabling
#            - name: Run Rector checks
#              run: composer rector-diff

            - name: Run CodeStyle checks
              run: composer cs-check

            - name: Codecept tests
              if: ${{ matrix.php-version == '7.4' }}
              run: composer test

            - name: Codecept tests with coverage
              if: ${{ matrix.php-version == '8.1' }}
              run: composer test-cover

            - name: Code Coverage Report
              if: success() && matrix.php-version == '8.1'
              uses: codecov/codecov-action@v3
              with:
                  file: ./tests/_output/coverage.xml

    prefer-lowest:
        name: "Prefer lowest checks"
        runs-on: "ubuntu-latest"
        env:
            APPLICATION_ENV: testing
        strategy:
            fail-fast: false
            matrix:
                php-version: [
                    '7.4'
                ]
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, intl, pdo_mysql, redis
                  tools: composer:v2

            - name: Composer get cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Composer cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer validate
              run: composer validate

            - name: Composer version
              run: composer --version

            - name: "Install lowest dependencies"
              run: composer update --prefer-lowest

            - name: Codecept tests
              run: composer test
